export const folderDataConsts = {
  CREATE_FOLDER_DATA_REQUEST: "CREATE_FOLDER_DATA_REQUEST",
  CREATE_FOLDER_DATA_SUCCESS: "CREATE_FOLDER_DATA_SUCCESS",
  CREATE_FOLDER_DATA_FAIL: "CREATE_FOLDER_DATA_FAIL",
  GET_FOLDER_DATA_REQUEST: "GET_FOLDER_DATA_REQUEST",
  GET_FOLDER_DATA_SUCCESS: "GET_FOLDER_DATA_SUCCESS",
  GET_FOLDER_DATA_FAIL: "GET_FOLDER_DATA_FAIL",
  GET_UPLOAD_FOLDER_DATA_REQUEST: "GET_UPLOAD_FOLDER_DATA_REQUEST",
  GET_UPLOAD_FOLDER_DATA_SUCCESS: "GET_UPLOAD_FOLDER_DATA_SUCCESS",
  GET_UPLOAD_FOLDER_DATA_FAIL: "GET_UPLOAD_FOLDER_DATA_FAIL",
  GET_FOLDER_FILE_DATA_REQUEST: "GET_FOLDER_FILE_DATA_REQUEST",
  GET_FOLDER_FILE_DATA_SUCCESS: "GET_FOLDER_FILE_DATA_SUCCESS",
  GET_FOLDER_FILE_DATA_FAIL: "GET_FOLDER_FILE_DATA_FAIL",
  GET_FOLDER_MOVE_DATA_REQUEST: "GET_FOLDER_MOVE_DATA_REQUEST",
  GET_FOLDER_MOVE_DATA_SUCCESS: "GET_FOLDER_MOVE_DATA_SUCCESS",
  GET_FOLDER_MOVE_DATA_FAIL: "GET_FOLDER_MOVE_DATA_FAIL",
  GET_UPLOAD_FOLDER_DATA_CLEAR: "GET_UPLOAD_FOLDER_DATA_CLEAR"
};

export function createFolderData(data) {
  return {
    type: folderDataConsts.CREATE_FOLDER_DATA_REQUEST,
    data
  };
}

export function getUserFolderData(data) {
  return {
    type: folderDataConsts.GET_FOLDER_DATA_REQUEST,
    data
  };
}

export function getUploadFolderData(data) {
  return {
    type: folderDataConsts.GET_UPLOAD_FOLDER_DATA_REQUEST,
    data
  };
}

export function getUploadFolderFileData(data) {
  return {
    type: folderDataConsts.GET_FOLDER_FILE_DATA_REQUEST,
    data
  };
}

export function getuserFolderMoveData(data, actionType) {
  return {
    type: folderDataConsts.GET_FOLDER_MOVE_DATA_REQUEST,
    data,
    actionType
  };
}

export function clearUploadStatus() {
  return {
    type: folderDataConsts.GET_UPLOAD_FOLDER_DATA_CLEAR
  };
}
